import type { SeedScenario } from "./types";

export const SCENARIOS: SeedScenario[] = [
  {
    title: "ALB returning 502 intermittently",
    slug: "alb-502-intermittent",
    summary:
      "Roughly 15% of requests to an Application Load Balancer return 502 Bad Gateway, but only for one of three target groups. Health checks pass.",
    context:
      "A public-facing order service sits behind an Application Load Balancer. The ALB forwards to three target groups in two Availability Zones: `blue` (4 EC2 instances running the v2.14 release) and `green` (4 instances running v2.15, which was rolled out 40 minutes before the errors began). Traffic is split by weighted target groups.\n\nThe application is a stateless Node service that opens a database connection pool on boot. There is no shared filesystem between instances.",
    symptoms:
      "- ~15% of requests fail with `502 Bad Gateway`\n- Failures are concentrated in the `green` target group only\n- ALB health checks report all targets healthy\n- CPU and memory on instances are within normal range\n- The application error rate is flat; no exceptions in logs",
    environment:
      "- ALB with weighted target groups, cross-zone load balancing enabled\n- 8x `t3.large` EC2 instances across 2 AZs, Auto Scaling group\n- AWS Load Balancer Controller on EKS previously, now moved to EC2\n- Release v2.15 deployed 40 minutes ago via CodeDeploy\n- Node 20, connection pool of 20 per instance",
    difficulty: "MEDIUM",
    isPremium: false,
    tags: ["aws", "alb", "networking", "troubleshooting", "incident"],
    durationMin: 12,
    rootCause:
      "The v2.15 release raised the per-instance connection pool from 20 to 60 while the RDS instance's `max_connections` was unchanged at 150. With 8 instances the cluster needed up to 480 connections, so the database began rejecting connections. Node's default `http.Server.keepAliveTimeout` of 5s is shorter than the ALB idle timeout of 60s, so the ALB occasionally reused an idle keep-alive connection that the app had already closed, producing a TCP RST between the load balancer and the target. The ALB surfaces this as 502, and it appeared on `green` only because that was where v2.15 was running.",
    fix:
      "Set the pool size to a value derived from the database limit divided by instance count, and align `keepAliveTimeout` above the ALB idle timeout so the server closes connections before the load balancer does. In this incident: pool to 15 per instance (120 total, under the RDS limit of 150), `server.keepAliveTimeout = 65000` and `server.headersTimeout = 66000`. Long term, put RDS Proxy in front of the database so connection multiplexing removes the coupling between instance count and pool size entirely.",
    prevention:
      "- Add RDS Proxy so application instance count no longer dictates connection count.\n- Put a check in CI that fails when a configured pool size times the maximum instance count exceeds the database's `max_connections`.\n- Alert on the ALB's `HTTPCode_ELB_502_Count` per target group, not aggregated, so a bad release localises immediately.\n- Alert on `HTTPCode_Target_Connection_Error_Metric` and on database connection utilisation above 80%.\n- Align keep-alive timeouts as a standard pattern in the service template so they are not tuned per release.",
    steps: [
      {
        prompt:
          "Before you change anything, what does a 502 from an ALB tell you, and what does it rule out?",
        options: [
          "The load balancer failed to get a valid response from a target; it does not implicate DNS or client connectivity",
          "The client could not resolve the load balancer's DNS name",
          "The load balancer's security group rejected the client request",
          "The database rejected the load balancer's health check",
        ],
        correct: [0],
        reasoning:
          "502 is generated by the load balancer after it has accepted the TCP connection from the client and failed to obtain a usable HTTP response from a target. That immediately makes client-side DNS and client-to-ALB connectivity unlikely causes, because the request demonstrably reached the load balancer. A 503 would point at no healthy targets, and a 504 at a timeout. This distinction saves a lot of wasted time, so establish it first.",
        code: [
          {
            language: "bash",
            caption: "Confirm the ALB is generating the 502, not a proxy in front of it",
            code: "aws elbv2 describe-load-balancers --names order-alb \\\n  --query 'LoadBalancers[].{DNS:DNSName,Scheme:Scheme,State:State.Code}'\n\n# Per-target-group error counts: where is it actually failing?\naws cloudwatch get-metric-statistics \\\n  --namespace AWS/ApplicationELB \\\n  --metric-name HTTPCode_Target_Connection_Error_Metric \\\n  --dimensions Name=LoadBalancer,Value=app/order-alb/1234 \\\n            Name=TargetGroup,Value=targetgroup/blue/abcd \\\n  --start-time 2026-09-28T10:00:00Z --end-time 2026-09-28T11:00:00Z \\\n  --period 300 --statistics Sum",
          },
        ],
      },
      {
        prompt:
          "Errors are only on the `green` target group, and `green` is the group that received the v2.15 release 40 minutes ago. What do you do next?",
        options: [
          "Roll back green to v2.14 to restore service, then investigate with the incident still owned",
          "Immediately scale down green to zero traffic",
          "Add more capacity to green",
          "Restart all instances on green",
        ],
        correct: [0],
        reasoning:
          "The correlation with the release is the strongest signal you have, and a rollback is fast, low-risk and reversible. Restoring service first is the right call when you have a working previous version; deep investigation happens after users are unblocked, with the change retained for debugging. Scale-to-zero or a mass restart destroy the evidence and change too many variables at once. Note the release correlation is a hypothesis until you prove the mechanism.",
        code: [
          {
            language: "bash",
            caption: "Shift all traffic to the known-good group while you investigate",
            code: "# Weigh blue at 100% and green at 0, then verify error rate falls\naws elbv2 modify-target-group-attributes \\\n  --target-group-arn arn:aws:elasticloadbalancing:ap-south-1:111:targetgroup/blue/abcd \\\n  --attributes Key=load_balancing.algorithm.attribute,Value=least_outstanding_requests\n\naws elbv2 modify-target-group \\\n  --target-group-arn arn:aws:elasticloadbalancing:ap-south-1:111:targetgroup/blue/abcd \\\n  --load-balancing-algorithm-type round_robin\n\naws cloudwatch get-metric-statistics \\\n  --namespace AWS/ApplicationELB \\\n  --metric-name HTTPCode_ELB_502_Count \\\n  --dimensions Name=TargetGroup,Value=targetgroup/blue/abcd \\\n  --start-time 2026-09-28T11:00:00Z --end-time 2026-09-28T11:15:00Z \\\n  --period 60 --statistics Sum",
          },
        ],
      },
      {
        prompt:
          "Service is restored. You now want to find the mechanism. ALB access logs show `d` (target duration) near zero and `target_status` recorded as `-` for the failing requests. What does that point to?",
        options: [
          "A TCP-level problem between the load balancer and the target, such as a connection reset, not an HTTP error from the app",
          "The target returned a 500 quickly",
          "The target was slow to respond",
          "The health check timed out",
        ],
        correct: [0],
        reasoning:
          "A recorded target duration near zero with no target status means the load balancer never completed an HTTP exchange with the target. The connection was established but then reset or closed before a response. If the app were returning a 500, you would see target_status 500 and a real duration. This points at connection lifecycle, not application logic.",
        code: [
          {
            language: "text",
            caption: "What an ALB access log looks like for a reset before any response",
            code: "http 2018-11-22T13:14:15.283641Z app/order-alb/1234 8.0.0.1:2817 10.0.3.45:8080 200000 0 1230173867668 0 0 \"-\" \"Mozilla/5.0\" ECDHE-RSA-AES128-GCM-SHA256 1.000000 1 200 200 0 \"-\" \"-\" \"-\" 24 \"-\" \"-\"",
          },
        ],
      },
      {
        prompt:
          "You suspect a keep-alive timeout mismatch between the app and the ALB. What is the danger zone and which side should close the connection?",
        options: [
          "If the app's keep-alive timeout is shorter than the load balancer's idle timeout, the app closes idle sockets the ALB still considers usable, causing intermittent resets. The server should close first, so set keepAliveTimeout above the load balancer's timeout.",
          "The ALB should always close first",
          "Timeouts do not matter if health checks pass",
          "The danger zone is when both timeouts are equal",
        ],
        correct: [0],
        reasoning:
          "The standard guidance is that the origin server should close the connection first, because it knows when it will need to recycle resources such as worker processes. Node's default `keepAliveTimeout` is 5 seconds, far below a load balancer idle timeout of 60 seconds, so the server closes sockets the load balancer still plans to reuse. The result is exactly this pattern: mostly-working traffic with a small fraction of resets, since only the requests that land on an idle-and-then-closed socket fail. The fix is `server.keepAliveTimeout` slightly above the load balancer timeout, with `headersTimeout` above that.",
        code: [
          {
            language: "javascript",
            caption: "Align Node keep-alive timeouts above the ALB idle timeout of 60s",
            code: "const server = http.createServer(app);\n\n// ALB idle timeout is 60s. Close slightly later than the load balancer\n// expects, so the server is never the side holding a dead socket.\nserver.keepAliveTimeout = 65_000;\nserver.headersTimeout = 66_000;\n\n// Node's default keepAliveTimeout is 5s, which is the actual root cause here.\nconsole.log('defaults were:', http.createServer().keepAliveTimeout);",
          },
        ],
      },
      {
        prompt:
          "The release also raised the database connection pool from 20 to 60. Why would that produce intermittent 502s rather than a clear database error?",
        options: [
          "The database starts rejecting connections, the app throws while handling a request, and the ALB reports the failed exchange as a 502 while the app's own error logs show it",
          "A larger pool always improves latency",
          "The ALB cannot handle more than 150 concurrent connections",
          "Connection pools only affect batch jobs",
        ],
        correct: [0],
        reasoning:
          "With 8 instances at 60 connections the cluster needs up to 480, well past the RDS limit of 150. Once connections are refused, the application throws while servicing a request; the load balancer receives a closed or failed connection and returns 502, while the application's own logs record the database error. So the 502 is a symptom and the database is the cause, which is why the timeline pointed at the release and not at the load balancer. This coupling is fragile precisely because pool size is per instance and instance count is chosen by Auto Scaling.",
        code: [
          {
            language: "bash",
            caption: "Confirm the database was refusing connections around the deploy",
            code: "aws cloudwatch get-metric-statistics \\\n  --namespace AWS/RDS \\\n  --metric-name DatabaseConnections \\\n  --dimensions Name=DBInstanceIdentifier,Value=orders-db \\\n  --start-time 2026-09-28T10:20:00Z --end-time 2026-09-28T11:00:00Z \\\n  --period 60 --statistics Maximum\n\naws rds describe-db-instances --db-instance-identifier orders-db \\\n  --query 'DBInstances[0].{Max:DBInstanceClassDetails,ParameterGroups:DBParameterGroups}'",
          },
          {
            language: "javascript",
            caption: "Size the pool from the database limit, not by wishful thinking",
            code: "// max_connections (150) x 80% headroom budget, divided by max instances (8)\nconst DB_MAX_CONNECTIONS = 150;\nconst MAX_INSTANCES = 8;\nconst RESERVE = 1; // admin sessions, migrations, on-call\n\nconst poolSize = Math.floor((DB_MAX_CONNECTIONS - RESERVE) / MAX_INSTANCES);\nconsole.log('per-instance pool size should be <=', poolSize); // <= 18",
          },
        ],
      },
      {
        prompt: "What is the durable fix so that scaling out can never again exhaust database connections?",
        options: [
          "Put RDS Proxy in front of the database so connections are multiplexed and instance count no longer dictates pool size",
          "Move to a larger RDS instance",
          "Add a second read replica",
          "Increase the pool size further",
        ],
        correct: [0],
        reasoning:
          "RDS Proxy pools and multiplexes connections, so hundreds of application connections share a small pool of database connections and survive instance changes. A larger instance raises `max_connections` but keeps the fragile coupling, and a read replica does not help the primary's connection limit at all. Removing the coupling entirely is the point: the failure happened because a per-instance setting interacted with an autoscaling group, and only changing one of those two leaves the trap in place.",
        code: [
          {
            language: "bash",
            caption: "Front the database with RDS Proxy and point the app at the proxy endpoint",
            code: "aws rds create-db-proxy \\\n  --db-proxy-name orders-proxy \\\n  --engine-family POSTGRESQL \\\n  --role-arn arn:aws:iam::111:role/rds-proxy-role \\\n  --auth-mode SECRETS \\\n  --vpc-subnet-ids subnet-aaaa1111 subnet-bbbb2222 \\\n  --vpc-security-group-ids sg-aaaa1111\n\n# Set target_max_connections to a value the database can sustain.\naws rds modify-db-proxy-target-group \\\n  --db-proxy-name orders-proxy \\\n  --target-group-name default \\\n  --connection-pool-config MaxConnectionsPercent=80",
          },
        ],
      },
    ],
  },

  {
    title: "Instance disk full despite low reported usage",
    slug: "linux-disk-full-inodes",
    summary:
      "A production instance reports 'No space left on device' while `df -h` shows 60% free space. Writes are failing on one service only.",
    context:
      "An Ubuntu 22.04 application server runs an API service, a log shipper and a Node process under systemd. A background job has been writing small files into `/var/lib/app/tmp` for several weeks. The disk is a 100GB gp3 volume mounted at `/`.\n\nThe team has restarted the failing service twice without effect, and has started to suspect the filesystem is corrupt.",
    symptoms:
      "- Writes to one service fail with `ENOSPC`\n- `df -h /` shows roughly 60% of the volume used\n- `du -sh /var/lib/app` reports only a few gigabytes\n- Other services on the same host write files successfully",
    environment:
      "- Ubuntu 22.04, ext4 on gp3, 100GB\n- systemd-managed services, logrotate configured for /var/log only\n- A cron job writing per-request cache files\n- Application uses a temporary directory for chunked uploads",
    difficulty: "MEDIUM",
    isPremium: false,
    tags: ["linux", "disk", "troubleshooting", "inodes"],
    durationMin: 10,
    rootCause:
      "The filesystem ran out of inodes, not data blocks. The background job was creating many tiny files in `/var/lib/app/tmp`, each consuming an inode while using almost no data, so `df -h` showed plenty of free space while `df -i` showed 100% inode usage. ext4 reserves a fixed percentage of inodes at format time (typically 5%), so inode exhaustion can occur while the block usage is still low, and it presents exactly like a full disk.",
    fix: "Remove the small files to reclaim inodes immediately (this works even at 100% inode usage because the unlink only needs an inode for the directory), then permanently fix the job so it writes to a single rotating file or to tmpfs instead of thousands of files. Raise `ext4` reserved blocks with `tune2fs -m 1` only if root-user writes are the specific problem; it does not address inode exhaustion.",
    prevention:
      "- Alert on inode usage (`df -i`) separately from block usage, at a lower threshold such as 70%.\n- Never let a service create unbounded files: use logrotate or a single file with size-based rotation.\n- Move genuinely temporary data to tmpfs (`tmpfs` in `/etc/fstab`) so it never touches the data volume.\n- Add a housekeeping cron job that prunes the temp directory by age rather than by size.\n- Run `tune2fs -i` periodically to track the inode ratio chosen at format time; consider a smaller inode ratio on ext4 for very small-file workloads, or use XFS, which allocates inodes dynamically.",
    steps: [
      {
        prompt:
        "The disk reports free space but writes fail. Which single command tells you whether the problem is blocks or inodes?",
        options: [
          "df -i, which shows inode usage per filesystem",
          "df -h, which shows block usage",
          "du -sh on the filesystem root",
          "mount",
        ],
        correct: [0],
        reasoning:
          "`df -h` reports data block usage, which is at 60%. `df -i` reports inode usage, and inodes are what the filesystem consumes when creating files. These are independent budgets: a filesystem with a million inodes runs out long before its blocks if the files are small. Always check both, and remember that block usage and inode usage can be at very different levels at the same moment.",
        code: [
          {
            language: "bash",
            caption: "Compare block usage against inode usage",
            code: "# Blocks: 60% used, looks healthy\ndf -h /\n\n# Inodes: this is where the problem is\ndf -i /\n\n# Filesystem      Inodes  IUsed  IFree IUse%  Mounted on\n# /dev/nvme1n1p1 6553600 6553600      0  100%  /",
          },
        ],
      },
      {
        prompt:
          "Inodes are at 100%. Which directory is most likely responsible, and how do you confirm it?",
        options: [
          "A directory accumulating many small files, confirmed by counting files per directory with `find | wc -l`",
          "The largest log file, confirmed with du",
          "The filesystem's lost+found directory",
          "The swap file",
        ],
        correct: [0],
        reasoning:
          "Large files consume blocks, not inodes. Inode exhaustion comes from enormous numbers of small files, so look for a directory with a huge file count. `du -sh` ranks by bytes and will point the wrong way; you need to count entries. The `/var/lib/app/tmp` directory in this environment is the obvious candidate given the described background job, and the count confirms it.",
        code: [
          {
            language: "bash",
            caption: "Rank directories by file count, not by size",
            code: "# Which directories hold the most files?\nfind /var /tmp /opt -xdev -type f -printf '%h\\n' 2>/dev/null \\\n  | sort | uniq -c | sort -rn | head -20\n\n# Total file count in the suspect directory\nfind /var/lib/app/tmp -type f | wc -l\n\n# Bytes are small even though the file count is enormous\ndu -sh /var/lib/app/tmp",
          },
        ],
      },
      {
        prompt:
          "You confirm `/var/lib/app/tmp` holds 6.5 million files. The filesystem is at 100% inodes. What happens if you now delete them?",
        options: [
          "It works. Unlinking frees inodes, so the filesystem becomes writable again immediately",
          "It fails, because the filesystem is already full and cannot perform the write to the journal",
          "It works, but you must reboot afterwards to clear the dentry cache",
          "It fails, because inodes can only be freed by a filesystem check",
        ],
        correct: [0],
        reasoning:
          "Removing a file requires freeing an inode, not allocating one, so deletion succeeds even at 100% inode usage. That is why the classic inode-exhaustion recovery is simply to delete the small files, and it is reversible in a way that a full-block filesystem is not. In contrast, creating a file needs a free inode and fails, which is exactly the `ENOSPC` your service is throwing.",
        code: [
          {
            language: "bash",
            caption: "Confirm inodes drop before restarting the service",
            code: "df -i /\n\n# Recover. Use -delete or xargs for large sets so you do not build a huge argv.\nfind /var/lib/app/tmp -type f -mtime +1 -delete\n\ndf -i /\n\n# Only restart the affected service once writes will succeed\nsystemctl restart app-api\nsystemctl status app-api --no-pager",
          },
        ],
      },
      {
        prompt:
          "How do you stop this recurring? The job writes per-request cache files that nothing ever cleans up.",
        options: [
          "Stop creating per-request files: use one rotating file, or write ephemeral data to tmpfs, and prune by age",
          "Add a cron job that deletes the directory whenever it exceeds 1GB",
          "Increase the volume size",
          "Increase the inode count with tune2fs",
        ],
        correct: [0],
        reasoning:
          "The structural fix is to stop generating unbounded small files. A single file with size-based rotation consumes one inode regardless of volume; tmpfs holds genuinely temporary data in memory so it never touches the data volume. A size-based cleanup cron job is a partial measure that still lets the count spike between runs, and growing the volume increases blocks, not inodes, so it does not address the actual constraint. tune2fs cannot add inodes after formatting; the inode count is fixed at mkfs time.",
        code: [
          {
            language: "bash",
            caption: "Option A: keep ephemeral data off the data volume entirely",
            code: "# /etc/fstab: tmpfs for scratch space, sized and bounded\n\"tmpfs /dev/shm tmpfs defaults,noatime,size=512M,mode=1777 0 0\"\n\n# Then point the app at it\n#   TMPDIR=/dev/shm/app-tmp\n",
          },
          {
            language: "ini",
            caption: "Option B: logrotate for the remaining log-style output",
            code: "/var/lib/app/tmp/*.json {\n  daily\n  rotate 3\n  maxsize 50M\n  missingok\n  compress\n  notifempty\n}",
          },
          {
            language: "bash",
            caption: "Prune by age rather than by size, and monitor both budgets",
            code: "# Age-based prune runs even when disk usage looks fine\nfind /var/lib/app/tmp -type f -mtime +1 -delete\n\n# Monitor inodes separately from blocks\n# Alert when inode usage > 70%, block usage > 75%\ndf -i --output=source,pcent / | tail -n +2",
          },
        ],
      },
      {
        prompt:
          "Separately, root-owned services started reporting ENOSPC while non-root writes still worked. Which knob addresses that specific symptom, and what does it not do?",
        options: [
          "Lower the reserved-block percentage with `tune2fs -m`, which frees blocks reserved for root; it does not add inodes",
          "Run tune2fs -i to increase inode count",
          "Remount with -o remount,rw",
          "Run fsck to rebuild the inode table",
        ],
        correct: [0],
        reasoning:
          "ext4 reserves about 5% of blocks for root by default, so a filesystem can be 'full' for ordinary users while root still has space. Lowering the reserve with `tune2fs -m 1 /dev/nvme1n1p1` addresses exactly that. It is a different failure mode from inode exhaustion: reserved blocks are about block availability for root, and reducing the reserve frees blocks, never inodes. Remounting read-write and running fsck do not create capacity, and fsck on a mounted filesystem is inappropriate.",
        code: [
          {
            language: "bash",
            caption: "Reduce root's reserved block percentage",
            code: "# Check current setting\ntune2fs -l /dev/nvme1n1p1 | grep -i reserved\n\n# Reduce root reserve from the default 5% to 1%\ntune2fs -m 1 /dev/nvme1n1p1\n\n# Note: this changes block reserve only, never inode count.\n# Inode count is fixed at mkfs time and cannot be increased afterwards.",
          },
        ],
      },
    ],
  },

  {
    title: "Pods stuck in CrashLoopBackOff",
    slug: "k8s-crashloopbackoff",
    summary:
      "After a routine image tag bump, roughly half the pods in a namespace are in CrashLoopBackOff. Events show the container starts and exits with code 1 within seconds.",
    context:
      "A stateless payments service runs as a Deployment of 6 replicas across a 3-node managed EKS cluster. It is managed by Helm and deployed by ArgoCD. The image tag was updated from `2.31.4` to `2.32.0` in the values file.\n\nThe service reads its database connection string from a Secret mounted at `/etc/secrets/db` and connects to an RDS instance in the same VPC.",
    symptoms:
      "- New pods enter CrashLoopBackOff; old pods on the previous tag are healthy\n- `kubectl describe pod` shows `Back-off restarting failed container`\n- Exit code 1 within 2-3 seconds of start\n- No OOMKilled events; CPU and memory within limits\n- Other deployments in the namespace are unaffected",
    environment:
      "- EKS 1.29 managed node group, 3x m6i.xlarge\n- ArgoCD syncing a Helm chart from git\n- Application restartPolicy Always under a Deployment\n- Readiness and liveness probes configured on /healthz with 5s initial delay",
    difficulty: "MEDIUM",
    isPremium: true,
    tags: ["kubernetes", "troubleshooting", "deployments", "incident"],
    durationMin: 14,
    rootCause:
      "The 2.32.0 image expects a new environment variable, `PAYMENTS_VAULT_ADDR`, that was not present in the existing Secret or ConfigMap. The application validates required configuration at startup and calls `os.Exit(1)` when it is missing, so the container exits cleanly-but-failed immediately, and the Deployment's restartPolicy makes Kubernetes retry with exponential backoff. The Helm chart change only updated the image tag; the new required Secret key was never added, so ArgoCD correctly synced the manifest and the app correctly refused to start. The lesson is that an image bump with a new required config dependency is a breaking change in disguise, and the chart should treat required config keys as part of the release.",
    fix:
      "Add the missing key to the Secret (via the sealed-secrets or external-secrets source, then force a rollout so the mounted file updates), and make the chart declare the value so it is versioned alongside the image. Because mounted Secret volumes refresh within roughly a minute, the pods will recover without a redeploy once the Secret updates, but a rollout restart is the deterministic option.",
    prevention:
      "- Validate required configuration at boot but fail with a single clear message, and expose a `/healthz` that reports `not ready` with the missing key name rather than exiting, so the failure is self-describing in the pod status.\n- Add a pre-deploy check in CI that diffs required config keys between the old and new image, using each release's documented config contract.\n- Use Helm `required` or JSON schema validation on values so a missing key fails at render time rather than at runtime.\n- Keep secrets in external-secrets with strict version control, and add an admission policy that blocks Deployments referencing an image tag that has no matching chart version.\n- Canary the rollout with ArgoCD so 10% of traffic exercises the new image first; a crash there is visible before full rollout.",
    steps: [
      {
        prompt:
          "The container exits with code 1 a few seconds after start. What is the first command to run, and why is `kubectl logs` not enough?",
          options: [
          "kubectl logs <pod> --previous, because the current container is still starting and logs of the failed instance are gone from the default call",
          "kubectl describe pod, to see events",
          "kubectl get pods -o wide",
          "docker logs on the node",
        ],
        correct: [0],
        reasoning:
          "With CrashLoopBackOff the container you would normally log into has just been replaced. `--previous` returns the output of the prior, failed instance, which is usually the only place the application's startup error appears. `kubectl describe` shows events and last state, which tells you the exit code but rarely the reason. So `--previous` first, then describe for context.",
        code: [
          {
            language: "bash",
            caption: "Get the failed instance's logs and the exit reason",
            code: "kubectl -n payments logs <pod-name> --previous --tail=100\n\nkubectl -n payments describe pod <pod-name> | \\\n  sed -n '/Containers:/,/Conditions:/p'\n\n# Watch the restart count climb\nkubectl -n payments get pods -w",
          },
        ],
      },
      {
        prompt:
          "The previous logs show `fatal: missing required config PAYMENTS_VAULT_ADDR`. How do you verify where this value is supposed to come from?",
          options: [
          "Compare the env and volume references in the live Deployment against the chart in git, and check the release notes for the new required config",
          "Restart the pods; the value will appear",
          "Check the image's entrypoint script in the container",
          "Look at the node's environment",
        ],
        correct: [0],
        reasoning:
          "A missing required config key is a contract mismatch between the image and its deployment manifest. The authoritative source is the chart in git, so diffing live spec against the committed manifest shows exactly what the release added or changed. The release notes for the image confirm whether the key is new and what it means. Restarting will not conjure a missing value; the deployment must be changed.",
        code: [
          {
            language: "bash",
            caption: "Compare the live Deployment against the committed chart",
            code: "# What the cluster actually has\nkubectl -n payments get deploy payments-api -o yaml | \\\n  sed -n '/envFrom:/,/volumeMounts:/p'\n\n# What git says should be there\ngit diff HEAD~1 -- charts/payments/values.yaml\n\n# Volume sources, where the mounted Secret keys live\nkubectl -n payments get deploy payments-api \\\n  -o jsonpath='{.spec.template.spec.volumes}' | jq",
          },
        ],
      },
      {
        prompt:
          "You add `PAYMENTS_VAULT_ADDR` to the Secret. The pods are still crashing. What do you need to know about how Secrets reach a running pod?",
          options: [
          "A Secret mounted as a volume updates in the running pod within about a minute via kubelet sync, but the app must re-read the file; env vars from a Secret do not update",
          "Secret changes require a full cluster restart",
          "Secret values are immutable once created",
          "Only newly created pods ever see the updated value",
        ],
        correct: [0],
        reasoning:
          "The kubelet syncs mounted ConfigMap and Secret volumes roughly every minute, so mounted files do update in place, and the atomic-writer symlink swap means apps see the new content without a partial read. But values sourced from `env` or `envFrom` are resolved at container start and never change, so a pod started before the Secret update keeps the stale environment. Which mechanism your app uses determines whether a rollout restart is required.",
        code: [
          {
            language: "bash",
            caption: "Secret mounted as volume: updates in ~1 min, no restart required",
            code: "kubectl -n payments patch secret payments-db \\\n  --type merge \\\n  -p '{\"stringData\":{\"PAYMENTS_VAULT_ADDR\":\"https://vault.internal:8200\"}}'\n\n# Wait for the kubelet to sync, then confirm the pod recovers on its own\nkubectl -n payments get pods -w",
          },
          {
            language: "yaml",
            caption: "If the app reads env vars, a rollout restart is required",
            code: "spec:\n  template:\n    spec:\n      containers:\n        - name: api\n          # env vars are resolved at start; they will NOT pick up Secret changes\n          env:\n            - name: PAYMENTS_VAULT_ADDR\n              valueFrom:\n                secretKeyRef:\n                  name: payments-db\n                  key: PAYMENTS_VAULT_ADDR",
          },
        ],
      },
      {
        prompt:
          "The pods recover. What change would have caught this before it reached production?",
        options: [
          "Make the chart declare required config keys with schema validation, and add a CI check that the image's required config matches the chart",
          "Add more replicas",
          "Increase the liveness probe failure threshold",
          "Set the image to always pull",
        ],
        correct: [0],
        reasoning:
          "This was a configuration contract failure, not a capacity or runtime problem, so the fix belongs in validation and release hygiene. Chart schema validation makes a missing required value fail at `helm template` time, in CI, before any rollout. A CI check that compares the image's documented required config against the chart catches the case where the image adds a new key. More replicas or probe tuning would not have surfaced the missing variable.",
        code: [
          {
            language: "yaml",
            caption: "Catch missing required config at render time with a values schema",
            code: "# charts/payments/values.schema.json\n{\n  \"$schema\": \"https://json-schema.org/draft-07/schema#\",\n  \"type\": \"object\",\n  \"required\": [\"image\", \"dbUrl\", \"vaultAddr\"],\n  \"properties\": {\n    \"vaultAddr\": { \"type\": \"string\", \"format\": \"uri\" }\n  }\n}",
          },
          {
            language: "bash",
            caption: "CI gate: render the chart and fail if a required key is absent",
            code: "# Fails fast in CI, before ArgoCD ever syncs the change\nhelm template payments charts/payments \\\n  --set image.tag=2.32.0 \\\n  --values charts/payments/values.yaml \\\n  | grep -q 'PAYMENTS_VAULT_ADDR' \\\n  || { echo 'chart is missing a required config key'; exit 1; }",
          },
        ],
      },
      {
        prompt:
          "What general practice would have kept this from being a full outage?",
        options: [
          "A canary rollout so a fraction of traffic exercises the new image and the crash is detected before full rollout",
          "Faster node provisioning",
          "Running the old and new version on the same node",
          "Disabling the liveness probe during deploys",
        ],
        correct: [0],
        reasoning:
          "A canary, either via ArgoCD analysis or a staged Deployment, sends a small slice of traffic to 2.32.0. If it crash-loops, the metric-based analysis aborts the rollout automatically and the majority never sees it. Disabling liveness during deploys is the opposite of good practice: liveness is exactly the signal that catches a process failing to start. Faster nodes do nothing for a configuration error, and co-locating versions changes nothing.",
        code: [
          {
            language: "yaml",
            caption: "ArgoCD canary: abort automatically when error rate rises",
            code: "spec:\n  strategy:\n    canary:\n      steps:\n        - setWeight: 10\n        - pause: { duration: 2m }\n        - analysis:\n            templates:\n              - templateName: error-rate-check\n        - setWeight: 50\n        - pause: { duration: 5m }\n        - setWeight: 100\n      analysis:\n        templates:\n          - name: error-rate-check\n            metric:\n              successCondition: result[0] < 1   # fail if error rate >= 1%\n              failureLimit: 2\n              interval: 1m\n              count: 3\n              provider:\n                prometheus:\n                  address: http://prometheus.monitoring:9090\n                  query: |\n                    sum(rate(http_requests_total{status=~\"5..\"}[2m]))\n                    /\n                    sum(rate(http_requests_total[2m]))",
          },
        ],
      },
    ],
  },

  {
    title: "Container cannot reach the database",
    slug: "docker-cannot-reach-database",
    summary:
      "An application container reports `ECONNREFUSED` connecting to a Postgres database that is running on the same Docker host and is reachable from the host itself.",
    context:
      "A Node.js API and a Postgres 16 database run as containers on a single Linux host using Docker Compose. The database container publishes port 5432 to the host. The application connects to `postgres` by service name in the Compose network. Since a refactor, the application fails at startup with a connection refused error.\n\nBefore the refactor, the application worked, connecting to `postgres:5432` over the Compose network.",
    symptoms:
      "- Application container exits with `ECONNREFUSED 172.18.0.3:5432`\n- `docker exec -it app ping -c 2 postgres` succeeds\n- Connecting to `localhost:5432` from the host works\n- The application log shows the resolved IP, not the hostname",
    environment:
      "- Docker Compose v2 on Ubuntu 22.04\n- Single bridge network, default bridge for the DB, custom bridge for the app after refactor\n- Postgres 16 container with published port 5432\n- App config uses `DATABASE_URL=postgres://app@postgres:5432/db`",
    difficulty: "MEDIUM",
    isPremium: false,
    tags: ["docker", "networking", "troubleshooting", "configuration"],
    durationMin: 8,
    rootCause:
      "The refactor moved the app onto a custom (user-defined) bridge network while Postgres remained on the Compose default network, or the app was switched to `network_mode: host`. Two containers can only resolve each other's names via Docker's embedded DNS if they share a user-defined network. On the default bridge, the name `postgres` does not resolve; the app fell back to something else and connected to a stale or wrong IP (172.18.0.3), which had nothing listening. The `ping` succeeding while the connection fails is the fingerprint: name resolution works, so both containers are on a shared network, but the port or listener on that specific address is wrong. The robust fix is to define both services on one explicitly named network in Compose so the dependency is declared and enforced, rather than relying on whichever network each container happens to default to.",
    fix:
      "Declare a single named network in the Compose file and attach both services to it, so `postgres` resolves via the embedded DNS to the correct container IP and the connection succeeds. Additionally, use a healthcheck with `depends_on: condition: service_healthy` so the app waits for Postgres to accept connections rather than assuming it is up as soon as the container starts.",
    prevention:
      "- Always declare an explicit named network and attach every service to it; never mix the legacy default bridge with a user-defined network for interdependent services.\n- Never use `network_mode: host` for a container that needs to resolve other container names.\n- Add a healthcheck to the database and gate the app on it with `depends_on: condition: service_healthy`.\n- Prefer the service name as the host in `DATABASE_URL` and never hardcode container IPs, which change on every recreate.\n- Have the app retry the initial connection with backoff anyway, so a slow-starting dependency cannot crash the process.\n- Add an integration smoke test in CI that runs the app container against a database container on the Compose network.",
    steps: [
      {
        prompt:
          "The app log shows it connected to `172.18.0.3:5432` and got ECONNREFUSED, yet `docker exec app ping postgres` works. What does that combination tell you?",
        options: [
          "Both containers share a network so the name resolves, but nothing is listening on that address at 5432, so the IP is stale or wrong",
          "The name does not resolve, so the app used a hardcoded IP",
          "Postgres is down",
          "The app is on the wrong port",
        ],
        correct: [0],
        reasoning:
          "`ping` succeeding proves Docker's embedded DNS is working for the name `postgres`, which only happens on a shared user-defined network. So resolution is fine and the app is not using a stale literal. The failure is that the address it reached has nothing listening on 5432, which means the resolved IP belongs to a different container or a stale endpoint. This fingerprint separates 'name resolution problem' from 'wrong endpoint', and it points straight at network topology.",
        code: [
          {
            language: "bash",
            caption: "Confirm which networks each container is actually on",
            code: "docker inspect -f '{{.Name}}: {{range $k,$v := .NetworkSettings.Networks}}{{$k}}={{$v.IPAddress}} {{end}}' app postgres\n\n# app on user-defined bridge, postgres on default bridge => they cannot\n# resolve each other by name. Both must share one network.",
          },
        ],
      },
      {
        prompt:
          "You confirm the app is on a custom bridge and Postgres is on the default bridge. What is the fix in Compose?",
        options: [
          "Declare one named network and attach both services to it",
          "Publish more ports",
          "Set the app to network_mode: host",
          "Give the app the postgres container's IP",
        ],
        correct: [0],
        reasoning:
          "Docker's embedded DNS resolves service names only for containers sharing a user-defined network. On the legacy default bridge there is no automatic name resolution, which is exactly why Compose creates a project network for you. Declaring one named network and attaching both services makes the dependency explicit and enforced. Publishing ports or host mode are irrelevant to container-to-container name resolution, and hardcoding an IP breaks the moment the container is recreated.",
        code: [
          {
            language: "yaml",
            caption: "One explicit network shared by both services",
            code: "services:\n  app:\n    build: ./app\n    environment:\n      DATABASE_URL: postgres://app@postgres:5432/db\n    networks: [appnet]\n    depends_on:\n      postgres:\n        condition: service_healthy\n\n  postgres:\n    image: postgres:16\n    environment:\n      POSTGRES_USER: app\n      POSTGRES_DB: db\n    ports: [\"5432:5432\"]   # host access only; app talks over appnet\n    networks: [appnet]\n    healthcheck:\n      test: [\"CMD-SHELL\", \"pg_isready -U app -d db\"]\n      interval: 5s\n      retries: 10\n\nnetworks:\n  appnet:\n    name: appnet",
          },
        ],
      },
      {
        prompt:
          "Both are on the same network now, but the app still exits on startup. What does Compose `depends_on` actually guarantee, and what does it not?",
        options: [
          "It guarantees the Postgres container has been created and started, not that it is accepting connections; use a healthcheck with condition: service_healthy",
          "It guarantees the database is ready to accept queries",
          "It waits for the database schema to finish migrating",
          "It guarantees DNS resolution for the service name",
        ],
        correct: [0],
        reasoning:
          "By default `depends_on` only controls start ordering: Compose starts Postgres first, then the app. Postgres typically needs a second or two to initialise its data directory, during which the port is not yet accepting connections, so the app crashes on first connect. Gating on `service_healthy` makes Compose wait for the healthcheck to pass, which is the correct pattern and is why `pg_isready` belongs in the healthcheck.",
        code: [
          {
            language: "bash",
            caption: "Prove the port is not listening during Postgres initialisation",
            code: "# Postgres is 'started' but not yet listening\ndocker compose logs postgres | tail -5\n# database system is ready to accept connections\n\ndocker compose up -d\ndocker compose logs app | grep -i 'connect'\n# Connection refused: the app started before Postgres was accepting\n\n# Verify the healthcheck actually reports healthy\ndocker inspect --format '{{.State.Health.Status}}' app-postgres-1",
          },
        ],
      },
      {
        prompt:
          "Even with a correct network and healthy gating, what defensive change makes the app resilient to a slow or restarting database?",
        options: [
          "Retry the initial connection with exponential backoff and a bounded total timeout instead of exiting on first failure",
          "Increase the container memory limit",
          "Set restart: always only",
          "Move DATABASE_URL to a build argument",
        ],
        correct: [0],
        reasoning:
          "Relying solely on startup ordering is brittle: the database can restart, fail over, or be slower than the healthcheck window, and a crash-on-first-connect turns a transient dependency blip into an outage. Bounded exponential backoff on connect handles the normal case and fails fast with a clear log when the dependency is genuinely down. `restart: always` masks the problem with a crash loop instead of handling it, and build args leak configuration into the image.",
        code: [
          {
            language: "javascript",
            caption: "Bounded retry with exponential backoff on first connect",
            code: "async function connectWithRetry(url, { attempts = 10, baseMs = 250 } = {}) {\n  for (let i = 1; i <= attempts; i += 1) {\n    try {\n      return await connect(url);\n    } catch (err) {\n      if (i === attempts) throw err;\n      const waitMs = Math.min(baseMs * 2 ** (i - 1), 10_000);\n      console.warn(`db connect attempt ${i}/${attempts} failed: ${err.message}; retrying in ${waitMs}ms`);\n      await new Promise((r) => setTimeout(r, waitMs));\n    }\n  }\n}\n\n// Use service name, never a container IP: IPs change on recreate.\nawait connectWithRetry(process.env.DATABASE_URL);",
          },
        ],
      },
    ],
  },

  {
    title: "Intermittent TLS handshake failures",
    slug: "networking-tls-intermittent",
    summary:
      "About 3% of HTTPS requests from a mobile client fail with `SSL handshake failure`. The same client talking to other hosts is fine, and failures cluster in the morning.",
    context:
      "A mobile client on cellular networks calls an API behind an AWS Application Load Balancer. Roughly 3% of handshakes fail with a TLS error. Failures are concentrated in the morning hours in one region. Desktop clients on the same API never report failures, and the CDN-served static assets load fine.\n\nThe server presents a certificate issued by a public CA with a full chain, served by nginx behind the ALB with TLS 1.2 and 1.3 enabled.",
    symptoms:
      "- `SSLHandshakeException` / `SSL error` on about 3% of requests, mobile only\n- Failures cluster by time of day and region\n- No server-side errors logged for the failing requests\n- A packet capture shows the ClientHello followed by no response or an abrupt close",
    environment:
      "- ALB with TLS 1.2/1.3, cipher suite list restricted\n- nginx 1.24 terminating TLS\n- Certificate chain with an intermediate, cross-signed\n- Clients on iOS and Android, various carriers",
    difficulty: "HARD",
    isPremium: true,
    tags: ["networking", "tls", "troubleshooting", "incident", "interview"],
    durationMin: 15,
    rootCause:
      "Some mobile clients in that region negotiate only ciphers from an older list (for example TLS 1.0/1.2 with an RSA key-exchange cipher the server had not whitelisted, or rejected the chain because a cached intermediate was stale on the device), and the server's strict cipher list plus a cross-signed intermediate produced inconsistent chain validation across carrier middleboxes. The morning clustering points to regional middleboxes and carrier caching of the chain. The fix is twofold: serve the full, correct chain including the intermediate and build the chain from the issuing CA's modern trust path, and widen the server's accepted ciphers/versions to include widely supported ones while keeping TLS 1.2+, plus enable OCSP stapling. This is a classic case where the server config looked correct and the fault lay in chain composition and client capability variation.",
    fix:
      "Serve the complete, correctly ordered chain (leaf plus intermediates up to, but not including, the root) built from the current trust path rather than a cross-signed one, and serve it without the root. Broaden the accepted protocols to TLS 1.2 and 1.3 with an ECDHE-preferring cipher list that still includes RSA key exchange for older mobile clients, disable TLS 1.0/1.1, and enable OCSP stapling. Verify with `openssl s_client` from multiple regions and with a real mobile client on each carrier.",
    prevention:
      "- Automate certificate chain monitoring: alert 30 days before expiry and validate the served chain from an external vantage point on a schedule, not just from inside the VPC.\n- Test TLS configuration against real mobile clients and regional middleboxes in a synthetic check, not only with `curl` from your own network.\n- Serve the full chain and pin the intermediate set; never rely on clients fetching it.\n- Enable OCSP stapling and monitor its success rate.\n- Keep a conservative cipher list that balances security with client compatibility, and review it when adding clients or regions.\n- Use a managed load balancer certificate (ACM) where possible so chain composition is handled and renewed automatically.",
    steps: [
      {
        prompt:
          "Failures are mobile-only, regional and time-clustered, with no server errors. What does that pattern most strongly suggest before you look at any config?",
        options: [
          "A difference in what those clients and middleboxes support, so the fault is on the client or network path rather than the application",
          "An application memory leak",
          "A database issue",
          "A misconfigured load balancer health check",
        ],
        correct: [0],
        reasoning:
          "The pattern is the diagnosis. No server-side errors means the request never became an application request, so look at the handshake and the path. Mobile-only points to client capability or carrier middlebox differences. Regional and time-clustered points to infrastructure specific to that region and hour, such as a middlebox or cached chain. This reframes the search toward TLS configuration, chain composition and client compatibility rather than application code.",
        code: [
          {
            language: "bash",
            caption: "Look for the handshake failing before HTTP, from the ALB",
            code: "# ALB logs: connection errors rather than HTTP responses\naws cloudwatch get-metric-statistics \\\n  --namespace AWS/ApplicationELB \\\n  --metric-name TLSClientNegotiationError_Metric \\\n  --dimensions Name=LoadBalancer,Value=app/api-alb/1234 \\\n  --start-time 2026-09-28T05:00:00Z --end-time 2026-09-28T09:00:00Z \\\n  --period 300 --statistics Sum",
          },
        ],
      },
      {
        prompt:
          "A capture shows the client sends a ClientHello and the connection closes with no ServerHello. Which server-side TLS settings should you verify first?",
        options: [
          "The enabled protocol versions and cipher suite list, since an unsupported version or cipher causes the server to drop the handshake",
          "The HTTP keep-alive timeout",
          "The client's DNS resolver",
          "The ALB health check path",
        ],
        correct: [0],
        reasoning:
          "A ClientHello with no ServerHello means the server rejected the hello. The usual reasons are a protocol version the server no longer allows (TLS 1.0/1.1 disabled) or a cipher suite the client offered that the server's list excludes, such as RSA key exchange. Both are silent rejections from the client's perspective, surfacing as a generic handshake error. So inspect the accepted versions and ciphers first; that is also why these failures look like 'nothing happened' in server logs.",
        code: [
          {
            language: "bash",
            caption: "Inspect exactly what the server offers",
            code: "# What the server supports\nopenssl s_client -connect api.example.com:443 -servername api.example.com -tls1_2 < /dev/null 2>/dev/null | \\\n  grep -E 'Protocol|Cipher|Verification'\n\n# What an old client might offer that we reject\nopenssl s_client -connect api.example.com:443 -servername api.example.com \\\n  -cipher 'DEFAULT:@SECLEVEL=0' -tls1 < /dev/null 2>&1 | head -20\n\n# Server config to check in nginx\n# ssl_protocols TLSv1.2 TLSv1.3;\n# ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:...:AES128-SHA;",
          },
        ],
      },
      {
        prompt:
          "Clients in the failing region are on older software with a partially cached intermediate. What server-side misconfiguration commonly turns that into a handshake failure, and what is correct?",
        options: [
          "Serving only the leaf certificate without the intermediate, or a cross-signed chain that some clients cannot build; serve the full chain from the issuing CA's modern path and omit the root",
          "Serving the root certificate as well, which confuses some clients",
          "Serving a certificate with too many SANs",
          "Using a wildcard when the clients expect a specific SAN",
        ],
        correct: [0],
        reasoning:
          "A server should send the leaf plus the intermediates needed to build a path, and should not send the root because clients already have it. Omitting the intermediate is the classic mistake: clients that cannot fetch it because AIA fetching is blocked (common on locked-down mobile and carrier networks) fail validation with no obvious error. Cross-signed intermediates can also produce a chain that some clients build incorrectly from a cached intermediate. Serving the correct chain from the current trust path, and ideally using ACM on the load balancer so AWS manages it, removes this class of failure.",
        code: [
          {
            language: "bash",
            caption: "Check the chain actually served, and verify a path builds to a trusted root",
            code: "echo | openssl s_client -connect api.example.com:443 -servername api.example.com 2>/dev/null | \\\n  sed -n '/Certificate chain/,/Server certificate/p'\n# 0 s:leaf   1 s:intermediate   (root must NOT be sent)\n\n# Confirm it verifies\nopenssl s_client -connect api.example.com:443 -servername api.example.com \\\n  -verify_return_error -CAfile /etc/ssl/certs/ca-certificates.crt </dev/null 2>&1 | grep 'Verify return code'\n# Verify return code: 0 (ok)",
          },
        ],
      },
      {
        prompt:
          "What should you do about cipher suites to restore compatibility without weakening security meaningfully?",
        options: [
          "Prefer ECDHE but retain widely supported RSA key-exchange and AES-GCM ciphers, keep TLS 1.2 and 1.3, and disable TLS 1.0/1.1",
          "Enable every cipher including NULL and export ciphers",
          "Downgrade to TLS 1.0 for compatibility",
          "Disable forward secrecy for faster handshakes",
        ],
        correct: [0],
        reasoning:
          "Compatibility and security are balanced by cipher choice, not by turning security off. Keeping ECDHE in front retains forward secrecy for modern clients while leaving RSA key-exchange and AES-GCM available for older ones; TLS 1.2 and 1.3 with 1.0/1.1 disabled still excludes the genuinely broken protocols. Enabling NULL or export ciphers or downgrading to TLS 1.0 would be a real vulnerability, and dropping forward secrecy to chase speed is the wrong trade for a handshake failure.",
        code: [
          {
            language: "bash",
            caption: "A compatibility-preserving cipher list",
            code: "# Modern-first, with widely supported fallbacks retained\nssl_protocols TLSv1.2 TLSv1.3;\nssl_prefer_server_ciphers off;\nssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA';\n\n# Staple OCSP so clients need not reach the CA (helps exactly the\n# region where AIA fetching is unreliable)\nssl_stapling on;\nssl_stapling_verify on;",
          },
        ],
      },
      {
        prompt:
          "How do you confirm the fix without waiting for real user reports?",
        options: [
          "Probe the TLS endpoint from multiple regions and with a real mobile client on each carrier on a schedule, and monitor negotiation errors",
          "Test only from the server's own region",
          "Ask the support team to confirm next week",
          "Rely on the ALB access logs alone",
        ],
        correct: [0],
        reasoning:
          "The bug only reproduced from specific regions and specific mobile clients, so your verification must cover those paths or it proves nothing. Synthetic probes from several AWS regions plus a real device on each affected carrier will catch a regression before users report it. Testing only from your own region reproduces exactly the condition that let the bug through in the first place, and ALB logs show errors only after they happen.",
        code: [
          {
            language: "bash",
            caption: "Scheduled multi-region handshake verification",
            code: "for region in ap-south-1 eu-west-1 us-east-1; do\n  echo \"== $region ==\"\n  aws ec2 describe-instance-status --region \"$region\" \\\n    --include-all-instances --filters \\\n      Name=instance-state-name,Values=running \\\n    --query 'InstanceStatuses[0].InstanceId' --output text\ndone\n\n# On each probe host, verify protocol support and chain\nfor host in api.example.com; do\n  for v in tls1_2 tls1_3; do\n    openssl s_client -connect \"$host:443\" -servername \"$host\" \"-$v\" </dev/null 2>/dev/null \\\n      | grep -q 'BEGIN CERTIFICATE' && echo \"$host $v OK\" || echo \"$host $v FAILED\"\n  done\ndone\n\n# Alert on negotiation errors per region\n# Metric: TLSClientNegotiationError_Metric > 0",
          },
        ],
      },
    ],
  },

  {
    title: "CI pipeline red intermittently for the same commit",
    slug: "cicd-flaky-pipeline",
    summary:
      "A pipeline that passes 9 times out of 10 fails intermittently on the same commit with a test timeout, yet the commit works locally every time.",
    context:
      "A test suite runs on ephemeral CI runners in containers. The suite includes integration tests that depend on a shared PostgreSQL container and on the current wall-clock time. Total runtime is around 14 minutes. Roughly 10% of runs fail with a single test timing out; rerunning the failed job passes.",
    symptoms:
      "- Roughly 10% of runs fail with `TimeoutError` on one flaky test\n- The same commit passes on retry\n- Local runs pass 100% of the time\n- Failures are not correlated with a particular test file in git history",
    environment:
      "- Ephemeral CI runners, 4 vCPU, 8GB RAM\n- Tests in containers with a shared Postgres service container\n- One test asserts on 'now' relative to a seeded record\n- CI runs the suite with `--maxWorkers=50%`",
    difficulty: "MEDIUM",
    isPremium: true,
    tags: ["ci-cd", "testing", "flaky-tests", "troubleshooting"],
    durationMin: 11,
    rootCause:
      "Two interacting sources of nondeterminism. First, a test asserts on the current wall-clock time while seeding a record with a relative timestamp, so it fails near a day or DST boundary or whenever the run crosses a date change. Second, tests share a Postgres database across parallel workers and depend on insertion order, so under higher CPU contention the interleaving changes and a test sees another test's rows or a lock wait that exceeds its timeout. Ephemeral runners make it worse because resources are contended across jobs, so timing shifts. The fix is to inject a fixed clock, isolate each worker's data (per-worker database or schema, or transaction rollback), and stop running the suite at half the machine's parallelism.",
    fix:
      "Inject a fixed `now` via a dependency-injectable clock so the test never reads the wall clock, and give each parallel worker its own database or schema with a truncated template so no state is shared. Reduce worker count to a level the runner can actually sustain, raise the timeout only after removing the nondeterminism, and quarantine the test short-term so the pipeline signal is trustworthy while the root cause is fixed.",
    prevention:
      "- Ban wall-clock reads in tests; inject a clock and use a fixed `now`.\n- Give every parallel worker an isolated database or schema so tests never share state or ordering.\n- Set worker count from measured runner capacity, not a percentage of an assumed core count.\n- Quarantine flakes with a fail-if-flaky policy so they cannot silently return to the blocking set.\n- Track flake rate per test over time and alert when it rises, so intermittent failures become visible before they erode trust.\n- Seed the CI environment with deterministic time, locale and timezone, and run a subset of the suite repeatedly (a 'flake hunt' job) to surface ordering bugs.",
    steps: [
      {
        prompt:
        "The same commit fails 10% of the time and passes on retry. What does that tell you about the cause?",
        options: [
          "The failure is nondeterministic, so the cause is timing, shared state, ordering or environment rather than the code change",
          "The commit is genuinely broken",
          "The CI runner image is corrupt",
          "The test assertions are wrong",
        ],
        correct: [0],
        reasoning:
          "Identical code failing intermittently points at nondeterminism: wall-clock reads, shared mutable state, test ordering, or resource contention. A genuinely broken commit fails every time. So the investigation shifts from 'what is wrong with this change' to 'what varies between runs', which points at the clock, parallel workers sharing a database, and CPU contention.",
        code: [
          {
            language: "bash",
            caption: "Confirm intermittency and start capturing flake rates",
            code: "# Run the same commit repeatedly and count failures\nfor i in $(seq 1 20); do\n  git rev-parse HEAD\ndone\n\n# Track which tests are intermittent, not just failing\n# Instrument the runner to record: test name, run number, duration, pass/fail",
          },
        ],
      },
      {
        prompt:
        "One test times out only sometimes. Which single change makes a timing-sensitive test deterministic?",
        options: [
          "Inject a fixed clock and assert against it, instead of reading the system time",
          "Increase the test timeout to 60 seconds",
          "Run the suite with more workers",
          "Mark the test as skipped",
        ],
        correct: [0],
        reasoning:
          "A test that reads the wall clock is nondeterministic by construction, because the result depends on when it runs, not on what it tests. Injecting a clock (a `now` parameter or a fake-timer library) makes the assertion depend only on inputs. Raising the timeout merely makes a real boundary bug slower to appear, and skipping removes coverage; more workers increases contention and makes it worse.",
        code: [
          {
            language: "javascript",
            caption: "Inject the clock so the test never reads wall time",
            code: "// Before: nondeterministic, fails near date/DST boundaries\n//   const record = await db.create({ createdAt: new Date() });\n//   expect(isRecent(record.createdAt, '1h')).toBe(true);\n\n// After: the clock is an injected dependency\nfunction createClock(fixedNow) {\n  return { now: () => fixedNow };\n}\n\ntest('record is recent relative to injected now', async () => {\n  const clock = createClock(new Date('2026-01-01T00:00:00Z'));\n  const record = await db.create({ createdAt: clock.now() });\n  expect(isRecent(record.createdAt, clock.now(), '1h')).toBe(true);\n});",
          },
        ],
      },
      {
        prompt:
        "Tests run in parallel against one Postgres container and share rows. Why does that cause intermittent timeouts?",
        options: [
          "Tests see each other's rows and lock contention, and under CPU contention the interleaving and wait times exceed the timeout",
          "Postgres cannot handle parallel connections",
          "Parallel tests corrupt the database",
          "The test timeout is too short",
        ],
        correct: [0],
        reasoning:
          "A shared database across parallel workers means state leaks between tests: one test's rows or uncommitted transaction can block or confuse another, and the interleaving depends on scheduling. Under CPU contention the lock waits grow, pushing a test past its timeout. Postgres handles concurrency fine; the problem is test isolation. The fix is a database or schema per worker, seeded from a template so each worker is independent.",
        code: [
          {
            language: "sql",
            caption: "Isolate each worker in its own database",
            code: "-- Create a template once, then clone per worker\nCREATE DATABASE app_test;\n-- run migrations and base seed into app_test\nCREATE DATABASE app_test_1 TEMPLATE app_test;\nCREATE DATABASE app_test_2 TEMPLATE app_test;\n\n-- Each worker points at its own database, so rows never cross\n-- Alternatively: one database, one schema per worker, search_path set per connection",
        },
        ],
      },
      {
        prompt:
        "What is the immediate step to stop this from eroding trust in the pipeline, and what is the real fix?",
        options: [
          "Quarantine the flaky test and retry it so the signal is trustworthy again; fix isolation and the clock properly rather than permanently skipping coverage",
          "Delete the test",
          "Disable parallel execution permanently",
          "Increase all timeouts and move on",
        ],
        correct: [0],
        reasoning:
          "A red pipeline 10% of the time teaches the team to click rerun, which destroys the signal. Quarantine with retry restores trust immediately while the real fix proceeds. Deleting a test loses coverage that may be catching something real, disabling parallelism slows everything and still leaves shared-state tests order-dependent, and inflating timeouts hides the nondeterminism. The durable work is clock injection, per-worker isolation, and a flake-rate metric so intermittency becomes visible.",
        code: [
          {
            language: "javascript",
            caption: "Quarantine with retry, and fail loudly if a quarantined test passes",
            code: "const QUARANTINED = new Set(['orders/legacy-refund.spec.ts']);\n\n// Quarantined tests: reported separately, do not fail the build, but\n// a PASS is escalated so a stale quarantine entry gets cleaned up.\nif (QUARANTINED.has(testFile) && testFailed) {\n  recordQuarantineFailure(testName);\n} else if (QUARANTINED.has(testFile) && testPassed) {\n  failBuild(`Quarantined test ${testName} now passes. Remove it from quarantine.`);\n}\n\n// Track flake rate per test to catch drift over time\nrecordFlakeRate(testName);",
          },
        ],
      },
    ],
  },
];
